algoritmo "Trabalho01"
var
s, n:real
inicio
escreval("-------------------------------------")
escreval("        Aumento de Salário           ")
escreval("-------------------------------------")
escreva("Digite o seu salário aqui:")
leia(s)
n <- s*18/100
escreval(" ")
escreval("-------------------------------------")
escreval("Seu salario passará a ser de ", s+n   )
escreval("-------------------------------------")
escreval("Trabalho realizado por João Pedro!")

fimalgoritmo
